services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: mdarj
      POSTGRES_PASSWORD: mdarj
      POSTGRES_DB: mdarj
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
